module.exports = {
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#313030',
        'error-container': '#ffdad6',
        'surface-bright': '#fcf9f8',
        'on-secondary-fixed': '#002204',
        'on-tertiary-container': '#fefcff',
        'primary-container': '#cd4700',
        tertiary: '#005ab7',
        secondary: '#1b6d24',
        'inverse-on-surface': '#f3f0ef',
        'surface-container': '#f0edec',
        'secondary-container': '#a0f399',
        'secondary-fixed': '#a3f69c',
        'surface-dim': '#dcd9d9',
        'surface-variant': '#e5e2e1',
        'on-primary-fixed': '#380d00',
        'on-surface-variant': '#5a4138',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#88d982',
        'on-surface': '#1c1b1b',
        'on-primary-fixed-variant': '#802a00',
        'on-tertiary-fixed-variant': '#00458f',
        'tertiary-fixed-dim': '#abc7ff',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#217128',
        'on-background': '#1c1b1b',
        'on-primary-container': '#fffbff',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#ffb59a',
        'tertiary-fixed': '#d7e2ff',
        'inverse-primary': '#ffb59a',
        primary: '#a43700',
        'primary-fixed': '#ffdbcf',
        'on-error': '#ffffff',
        'surface-tint': '#a83900',
        'surface-container-low': '#f6f3f2',
        'outline-variant': '#e3bfb2',
        'surface-container-high': '#ebe7e7',
        'tertiary-container': '#0072e4',
        'on-secondary-fixed-variant': '#005312',
        'on-tertiary-fixed': '#001b3f',
        outline: '#8f7066',
        background: '#fcf9f8',
        'surface-container-highest': '#e5e2e1',
        'on-primary': '#ffffff',
        surface: '#fcf9f8',
        'on-secondary': '#ffffff',
      },
      spacing: {
        'container-margin': '16px',
        base: '4px',
        sm: '12px',
        xs: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '12px',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-lg': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
        'label-sm': ['Inter'],
        'price-display': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'price-display': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'price-display-sm': ['16px', { lineHeight: '20px', fontWeight: '700' }],
      },
    },
  },
}
